# Generated by Django 5.2.8 on 2025-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_designators', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('identified_mpn', models.CharField(blank=True, max_length=255, null=True)),
                ('identified_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
