# Generated by Django 5.2.8 on 2025-12-01 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='boms/')),
                ('is_master', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('mpn', 'manufacturer')},
            },
        ),
        migrations.CreateModel(
            name='BOMEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reference_designators', models.CharField(max_length=1000)),
                ('bom_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bom.bomfile')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.part')),
            ],
        ),
    ]
